import type { Metadata } from "next";
import Image from "next/image";
import Link from "@/components/site-link";
import { Reveal } from "@/components/reveal";

export const metadata: Metadata = { title: "About", description: "The story, architecture, nature, and hospitality behind Svara Villa." };

export default function AboutPage() { return <main id="main-content"><section className="page-hero about-hero"><Image src="/images/svara-hero.png" alt="Svara Villa settled above a lush tropical valley" fill priority sizes="100vw" /><div className="page-hero-shade" /><div><p className="eyebrow">Our story</p><h1>Built for<br /><em>being here.</em></h1></div></section>
  <section className="about-opening"><p className="section-kicker">A simple idea</p><Reveal><h2>We wanted to make a place that asks less of you.</h2></Reveal><div><p>Svara began with a patch of land, a stand of old palms, and a belief that a good stay should feel generous without feeling grand.</p><p>The villas were drawn around what was already here. The service followed the same thought: present when useful, almost invisible when not.</p></div></section>
  <section className="about-chapters"><article><div className="about-image"><Image src="/images/villa-one.jpg" alt="Natural stone and timber villa architecture" fill sizes="(max-width: 800px) 100vw, 55vw" /></div><div><p className="section-kicker">01 · Architecture</p><h2>Open to the weather.</h2><p>Deep rooflines, cross-breezes, local stone, and timber screens keep each villa cool and connected to its garden.</p></div></article><article><div className="about-image"><Image src="/images/garden.jpg" alt="A villa held within a tropical garden" fill sizes="(max-width: 800px) 100vw, 55vw" /></div><div><p className="section-kicker">02 · Nature</p><h2>The garden came first.</h2><p>Existing trees shaped the footprint. Native planting brings shade, privacy, and the small morning soundtrack of birds and leaves.</p></div></article><article><div className="about-image"><Image src="/images/breakfast.jpg" alt="Thoughtfully prepared villa breakfast" fill sizes="(max-width: 800px) 100vw, 55vw" /></div><div><p className="section-kicker">03 · Hospitality</p><h2>Care, without ceremony.</h2><p>We notice the practical things, remember how you take your coffee, and leave enough space for the stay to feel like your own.</p></div></article></section>
  <section className="about-quote"><blockquote>“Luxury, to us, is time that feels entirely yours.”</blockquote><span>— The Svara philosophy</span></section><section className="simple-cta"><p className="section-kicker">Come stay awhile</p><h2>See it for yourself.</h2><Link className="button button-light" href="/villas">Explore the villas</Link></section></main>; }
